# Generated by Django 3.2.5 on 2021-07-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_orderline_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salestarget',
            unique_together={('year', 'month')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('is_shipped', False)), fields=['is_shipped'], name='unshipped_orders'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('is_shipped', False)), fields=('customer', 'is_shipped'), name='limit_pending_orders'),
        ),
    ]
