# Generated by Django 3.2.5 on 2021-07-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210704_1420'),
    ]

    class Migration(migrations.Migration):
        operations = [
            migrations.RunSQL(
                sql='''
                CREATE VIEW unshipped_orders AS
                SELECT * FROM orders_order
                WHERE is_shipped = false;
                ''',
                reverse_sql='''
                DROP VIEW unshipped_orders;
                ''',
            )
        ]
